param(
  [string]$TaskName = "CodexBridge-Weixin",
  [string]$RootDir = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path,
  [string]$StateDir = "",
  [string]$EnvFile = "",
  [string]$HomeDir = "",
  [string]$DefaultCwd = "",
  [switch]$AtStartup
)

$ErrorActionPreference = "Stop"

function Find-CommandPath([string[]]$Names) {
  foreach ($Name in $Names) {
    $Command = Get-Command $Name -ErrorAction SilentlyContinue
    if ($Command) {
      return $Command.Source
    }
  }
  return ""
}

function Quote-WindowsArgument([string]$Value) {
  return "`"$Value`""
}

function Resolve-ServiceHomeDir([string]$RequestedHomeDir, [string]$ResolvedRootDir) {
  if ($RequestedHomeDir) {
    $Resolved = Resolve-Path $RequestedHomeDir -ErrorAction SilentlyContinue
    if ($Resolved) {
      return $Resolved.Path
    }
    return $RequestedHomeDir
  }

  if ($env:CODEXBRIDGE_SERVICE_HOME) {
    $Resolved = Resolve-Path $env:CODEXBRIDGE_SERVICE_HOME -ErrorAction SilentlyContinue
    if ($Resolved) {
      return $Resolved.Path
    }
    return $env:CODEXBRIDGE_SERVICE_HOME
  }

  $CurrentIdentity = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
  if ($CurrentIdentity -ne "NT AUTHORITY\SYSTEM" -and $env:USERPROFILE) {
    return $env:USERPROFILE
  }

  $RootMatch = [regex]::Match($ResolvedRootDir, "^[A-Za-z]:\\Users\\[^\\]+")
  if ($RootMatch.Success) {
    return $RootMatch.Value
  }

  try {
    $LoggedOnUser = (Get-CimInstance Win32_ComputerSystem).UserName
    if ($LoggedOnUser -and $LoggedOnUser.Contains("\")) {
      $UserName = $LoggedOnUser.Split("\")[-1]
      $Candidate = Join-Path (Join-Path $env:SystemDrive "Users") $UserName
      if (Test-Path $Candidate) {
        return $Candidate
      }
    }
  } catch {}

  if ($env:USERPROFILE) {
    return $env:USERPROFILE
  }

  throw "Could not resolve service home directory. Pass -HomeDir explicitly."
}

function Resolve-ServiceAppData([string]$ResolvedHomeDir) {
  if ($env:APPDATA -and $env:APPDATA -notlike "*\systemprofile\*") {
    return $env:APPDATA
  }
  return Join-Path $ResolvedHomeDir "AppData\Roaming"
}

$NodeBin = Find-CommandPath @("node.exe", "node")
if (-not $NodeBin) {
  throw "node was not found in PATH"
}
$WScriptBin = Find-CommandPath @("wscript.exe", "wscript")
if (-not $WScriptBin) {
  throw "wscript was not found in PATH"
}

$HomeDir = Resolve-ServiceHomeDir $HomeDir $RootDir
if (-not $StateDir) {
  $StateDir = Join-Path $HomeDir ".codexbridge"
}
if (-not $EnvFile) {
  $EnvFile = Join-Path (Resolve-ServiceAppData $HomeDir) "codexbridge\weixin.service.env"
}

$CodexBin = Find-CommandPath @("codex.exe", "codex.cmd", "codex.bat", "codex")
$ConfigDir = Split-Path -Parent $EnvFile
$LogDir = Join-Path $StateDir "logs"
$CodexHome = Join-Path $HomeDir ".codex"

New-Item -ItemType Directory -Force -Path $ConfigDir, $LogDir | Out-Null

if (-not (Test-Path $EnvFile)) {
  @(
    "# Generated by scripts/service/install-windows-task.ps1",
    "# Safe to edit after install.",
    "",
    "WEIXIN_ACCOUNT_ID=",
    "WEIXIN_DM_POLICY=open",
    "WEIXIN_GROUP_POLICY=disabled",
    "",
    "CODEX_DEFAULT_PROVIDER_PROFILE_ID=openai-default",
    "CODEX_HOME=$CodexHome",
    "CODEX_REAL_BIN=$CodexBin",
    "",
    "CODEXBRIDGE_DEBUG_WEIXIN=0"
  ) | Set-Content -Encoding UTF8 -Path $EnvFile
} else {
  $EnvContent = Get-Content -Path $EnvFile -Raw
  if ($EnvContent -notmatch "(?m)^CODEX_HOME=") {
    Add-Content -Encoding UTF8 -Path $EnvFile -Value "CODEX_HOME=$CodexHome"
  }
}

Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue | Out-Null

Write-Host "Auto-start disabled: the Weixin bridge no longer installs a scheduled task."
Write-Host "Use scripts/service/open-weixin-admin.ps1 or the desktop shortcut to start it manually."
Write-Host "Home dir: $HomeDir"
Write-Host "Environment file: $EnvFile"
